-- Whether the workspace's branch name was auto-generated by the daemon at
-- create time (friendly slug naming) rather than supplied by the caller.
-- Drives the `workspace.delete` branch-cleanup guard (parity with the TS
-- `removeGitWorktree` `branchName === workspaceId` check, where the workspace
-- id doubles as the auto-generated branch name): only a branch the workspace
-- itself named is ever deleted alongside the worktree. Defaults to 0
-- (caller-supplied / unknown) so pre-existing rows never lose a branch.
ALTER TABLE workspace ADD COLUMN branch_auto_generated INTEGER NOT NULL DEFAULT 0;
