-- config.toml migration: non-secret true settings moved out of SQLite into
-- `<data_dir>/config.toml` (registry-backed). Delete their rows; the
-- `settings` table remains for machine-state blobs (workspace.changeHistory,
-- workspaceInitializer.state, repos.known, endUserRules, permissions.rules,
-- userRules, workspaceRules) and any dynamic non-TOML keys. Configuration is
-- reset from scratch (no value import), so a targeted DELETE suffices. The
-- key list is a frozen copy of the registry's KNOWN_PATHS at migration time —
-- migrations are immutable and must not reference runtime constants.

DELETE FROM settings WHERE key IN (
  'providers.active',
  'providers.enabled',
  'providers.paths',
  'model.default',
  'model.providerDefaults',
  'model.workspaceOverrides',
  'backgroundAgents.defaultModel',
  'backgroundAgents.typeOverrides',
  'backgroundAgents.providerSettings',
  'specialists.default',
  'workspace.branchPrefix',
  'workspace.worktreesLocation',
  'workspace.sshKeyPath',
  'workspace.defaultShell',
  'workspace.autoFetch',
  'workspace.cowIsolation',
  'git.autoCommit',
  'mcp.enableUserServers',
  'mcp.disabledServers',
  'notifications.enabled',
  'notifications.soundEnabled',
  'notifications.soundOnlyWhenUnfocused',
  'notifications.volume',
  'rtk.enabled',
  'server.listenMode',
  'server.socketPath',
  'server.bindAddress',
  'server.port',
  'server.originAllowList',
  'server.wsApi.enabled',
  'server.wsApi.port',
  'server.tls.enabled',
  'server.auth.enabled',
  'sourceControl.activeProvider',
  'sourceControl.github.tokenSource',
  'sourceControl.github.apiBaseUrl',
  'accounts.sentry.organization',
  'ai.apiUrl',
  'ai.model',
  'ai.temperature',
  'ai.maxTokens',
  'ai.streamingSpeed',
  'context.enabled',
  'context.auggiePath',
  'context.allowIndexing',
  'storage.dataDir',
  'workspaces.root',
  'logging.level',
  'agents.maxConcurrent',
  'agents.idleReapMinutes',
  'events.streamRetentionHours'
);
