//! Word lists backing [`super`] (TS `local-slug-generator.ts` stop/action
//! words; adjective/animal dictionaries in the spirit of the reference's
//! `unique-names-generator` sets, pre-filtered to `^[a-z]{2,15}$`).

/// Common stop words filtered out of prompt-derived slugs.
pub(super) const STOP_WORDS: &[&str] = &[
    "a",
    "an",
    "the",
    "and",
    "or",
    "but",
    "in",
    "on",
    "at",
    "to",
    "for",
    "of",
    "with",
    "by",
    "from",
    "as",
    "is",
    "was",
    "are",
    "were",
    "been",
    "be",
    "have",
    "has",
    "had",
    "do",
    "does",
    "did",
    "will",
    "would",
    "could",
    "should",
    "may",
    "might",
    "must",
    "shall",
    "can",
    "need",
    "dare",
    "optimistic",
    "ought",
    "used",
    "that",
    "this",
    "these",
    "those",
    "i",
    "me",
    "my",
    "we",
    "our",
    "you",
    "your",
    "he",
    "him",
    "his",
    "she",
    "her",
    "it",
    "its",
    "they",
    "them",
    "their",
    "what",
    "which",
    "who",
    "whom",
    "whose",
    "where",
    "when",
    "why",
    "how",
    "all",
    "each",
    "every",
    "both",
    "few",
    "more",
    "most",
    "other",
    "some",
    "such",
    "no",
    "nor",
    "not",
    "only",
    "own",
    "same",
    "so",
    "than",
    "too",
    "very",
    "just",
    "also",
    "now",
    "here",
    "there",
    "then",
    "please",
    "help",
    "want",
    "like",
    "make",
    "get",
    "let",
    "put",
    "take",
    "give",
    "go",
    "come",
    "see",
    "look",
    "find",
    "use",
    "new",
    "way",
    "thing",
    "things",
];

/// Action words that pair well with a noun in a slug.
pub(super) const ACTION_WORDS: &[&str] = &[
    "add",
    "fix",
    "update",
    "create",
    "remove",
    "delete",
    "refactor",
    "improve",
    "implement",
    "build",
    "design",
    "test",
    "debug",
    "optimize",
    "migrate",
    "upgrade",
    "setup",
    "config",
    "deploy",
    "integrate",
    "connect",
    "sync",
    "validate",
    "check",
    "verify",
    "review",
    "clean",
    "format",
    "lint",
    "type",
];

/// Adjectives for random `adjective-animal` slugs.
pub(super) const ADJECTIVES: &[&str] = &[
    "amber",
    "ancient",
    "autumn",
    "billowing",
    "bitter",
    "black",
    "blue",
    "bold",
    "brave",
    "bright",
    "broken",
    "calm",
    "cobalt",
    "cold",
    "cool",
    "crimson",
    "curly",
    "damp",
    "dark",
    "dawn",
    "delicate",
    "divine",
    "dry",
    "empty",
    "falling",
    "fancy",
    "flat",
    "floral",
    "fragrant",
    "frosty",
    "gentle",
    "golden",
    "green",
    "hidden",
    "holy",
    "icy",
    "jolly",
    "late",
    "lingering",
    "little",
    "lively",
    "long",
    "lucky",
    "misty",
    "morning",
    "muddy",
    "mute",
    "nameless",
    "noisy",
    "odd",
    "old",
    "orange",
    "patient",
    "plain",
    "polished",
    "proud",
    "purple",
    "quiet",
    "rapid",
    "raspy",
    "red",
    "restless",
    "rough",
    "round",
    "royal",
    "shiny",
    "shrill",
    "shy",
    "silent",
    "silver",
    "small",
    "snowy",
    "soft",
    "solitary",
    "sparkling",
    "spring",
    "square",
    "steep",
    "still",
    "summer",
    "sweet",
    "throbbing",
    "tight",
    "tiny",
    "twilight",
    "wandering",
    "weathered",
    "white",
    "wild",
    "winter",
    "wispy",
    "withered",
    "yellow",
    "young",
];

/// Animals for random `adjective-animal` slugs.
pub(super) const ANIMALS: &[&str] = &[
    "badger", "bat", "bear", "beaver", "bee", "bison", "boar", "buffalo", "camel", "cat",
    "cheetah", "cobra", "condor", "cougar", "coyote", "crab", "crane", "crow", "deer", "dingo",
    "dolphin", "donkey", "dove", "dragon", "duck", "eagle", "elephant", "elk", "falcon", "ferret",
    "finch", "fox", "frog", "gazelle", "gecko", "gibbon", "giraffe", "goat", "goose", "gopher",
    "gorilla", "hare", "hawk", "hedgehog", "heron", "horse", "hound", "ibis", "iguana", "jackal",
    "jaguar", "kangaroo", "koala", "lark", "lemur", "leopard", "lion", "lizard", "llama",
    "lobster", "lynx", "magpie", "marmot", "meerkat", "mole", "moose", "mouse", "mule", "newt",
    "ocelot", "octopus", "orca", "osprey", "otter", "owl", "panda", "panther", "parrot", "pelican",
    "penguin", "pheasant", "pigeon", "pony", "puffin", "puma", "python", "quail", "rabbit",
    "raccoon", "ram", "raven", "robin", "salmon", "seal", "shark", "sheep", "sloth", "snail",
    "sparrow", "squid", "squirrel", "stork", "swan", "tiger", "toad", "trout", "turtle", "viper",
    "walrus", "weasel", "whale", "wolf", "wombat", "wren", "yak", "zebra",
];
