import assert from 'node:assert/strict';
import {readdirSync,lstatSync,readFileSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
const files=new Set(['setup-summary.json','native-native-receipts.json','native-native-result.json','install-receipts.json','acceptance-receipt.json','dependency-result.json','controls.tap','policy-controls.tap','policy-receipt.json','latch-result.json','resolution-control-result.json','resolution-receipt.json','version-receipts.json','tool-provenance.json']);
const exact=(obj,keys)=>assert.deepEqual(Object.keys(obj).sort(),keys.split(' ').sort());
const hash=x=>assert(/^[a-f0-9]{64}$/.test(x));
const integer=x=>assert(Number.isSafeInteger(x)&&x>=0);
const safePath=x=>assert(typeof x==='string'&&x.length<=1024&&!x.includes('..')&&!/^[\\/]|:/.test(x)&&!/[\x00-\x1f]/.test(x));
function receipt(x){exact(x,'stage reason win32 rootPid originalExit rootCreation written read assigned resumed overflow readerError activeZero rootSignalled readerDone maximumActive snapshots elapsedMs observedMembers interventions');assert(['initial','job','create_suspended','assign','resume','running','disposal','argument','native_or_io'].includes(x.stage));assert(['none','assignment_failed','completed','output_cap','reader_error','deadline','setup_or_observation_error'].includes(x.reason));assert(Number.isInteger(x.win32));assert(/^[0-9]{1,20}$/.test(x.rootCreation));for(const k of ['rootPid','originalExit','written','read','maximumActive','snapshots','elapsedMs'])integer(x[k]);for(const k of ['assigned','resumed','overflow','readerError','activeZero','rootSignalled','readerDone'])assert.equal(typeof x[k],'boolean');assert(x.observedMembers.length<=256);x.observedMembers.forEach(integer);assert(x.interventions.length<=2);assert(x.interventions.every(v=>['terminate_unresumed_process_handle','terminate_owned_job'].includes(v)));}
function dep(x){exact(x,'stage outcome behavioralInvocations downloadsBytes packages resolution mirrorUnmodified optionalExclusions tarParser');assert.equal(x.stage,'setup');assert.equal(x.outcome,'PASS');assert.equal(x.behavioralInvocations,0);integer(x.downloadsBytes);assert.equal(x.mirrorUnmodified,true);assert.deepEqual(x.optionalExclusions,[]);assert.equal(x.tarParser,'Regular files/directories only; unsupported archive features stop setup.');assert.equal(x.packages.length,2);assert.deepEqual(x.packages.map(g=>g.prefix),['.pi-acp-test','.pi-runtime-test']);
 for(const group of x.packages){exact(group,'prefix packages fileInventory generatedFiles qualification');assert(['.pi-acp-test','.pi-runtime-test'].includes(group.prefix));assert.equal(group.qualification,'Generated .bin shims hashed but not executed; no optional/platform exclusion permitted. Tar-attributed bytes are current install evidence, not a historical installed tree.');assert.equal(group.packages.length,group.prefix==='.pi-acp-test'?9:239);assert.equal(new Set(group.packages.map(p=>p.packagePath)).size,group.packages.length);for(const p of group.packages){exact(p,'packagePath version resolved integrity integrityInHistoricalRecord tarSha256');safePath(p.packagePath);assert(/^[0-9A-Za-z.+_-]{1,100}$/.test(p.version));const u=new URL(p.resolved);assert.equal(u.origin,'https://registry.npmjs.org');assert(!u.username&&!u.password&&!u.search&&!u.hash);assert(/^sha512-[A-Za-z0-9+/]+=*$/.test(p.integrity));assert.equal(Buffer.from(p.integrity.slice(7),'base64').length,64);assert.equal(typeof p.integrityInHistoricalRecord,'boolean');hash(p.tarSha256);}assert(Object.keys(group.fileInventory).length<=100000);for(const [k,v]of Object.entries(group.fileInventory)){safePath(k);hash(v);}group.generatedFiles.forEach(safePath);}
 assert.equal(x.resolution.length,4);assert.deepEqual(x.resolution.map(r=>r.name+':'+r.condition),['@agentclientprotocol/sdk:import','@agentclientprotocol/sdk:require','cross-spawn:import','cross-spawn:require']);for(const r of x.resolution){exact(r,'name condition relativePath sha256');assert(['import','require'].includes(r.condition));assert(['@agentclientprotocol/sdk','cross-spawn'].includes(r.name));safePath(r.relativePath);hash(r.sha256);}}
const policyNames=JSON.parse(readFileSync(new URL('./upload-expected.json',import.meta.url),'utf8'));
const nativeNames=['assigned-before-entry','assignment-refusal-unresumed','original-nonzero','argument-quoting','deadline-disposal','grandchild-disposal','retired-parent-disposal','stream-cap','accepted46-native'];
const latchNames=['safe-no-child','safe-unassigned-stopped','safe-disposed','unresolved-active','unresolved-root','unresolved-reader','reader-error','exception-before-receipt'];
function tap(data,expected){const lines=data.trimEnd().split(/\r?\n/),results=[],subtests=[];for(const line of lines){let m;if((m=line.match(/^# Subtest: (.*)$/)))subtests.push(m[1]);else if((m=line.match(/^ok ([0-9]+) - (.*)$/))){assert.equal(Number(m[1]),results.length+1);results.push(m[2]);}else assert(/^(TAP version 13|1\.\.[0-9]+|  ---|  \.\.\.|  duration_ms: [0-9.]+|  type: 'test'|# (tests|suites|pass|fail|cancelled|skipped|todo) [0-9]+|# duration_ms [0-9.]+)$/.test(line));}
 assert.deepEqual(results,expected);assert.deepEqual(subtests,expected);for(const line of ['TAP version 13','1..'+expected.length,'# tests '+expected.length,'# suites 0','# pass '+expected.length,'# fail 0','# cancelled 0','# skipped 0','# todo 0'])assert.equal(lines.filter(x=>x===line).length,1);for(const key of ['tests','suites','pass','fail','cancelled','skipped','todo'])assert.equal(lines.filter(x=>x.startsWith('# '+key+' ')).length,1);}
function success(r){receipt(r);assert.equal(r.reason,'completed');assert.equal(r.originalExit,0);assert(r.assigned&&r.resumed&&r.activeZero&&r.rootSignalled&&r.readerDone&&!r.readerError&&!r.overflow);assert.deepEqual(r.interventions,[]);}
function tools(x){exact(x,'status before afterEqual nodeRuntime npmRuntimeVersion compiler');assert.equal(x.status,'PASS');assert.equal(x.afterEqual,true);exact(x.before,'node npm powershell runtime');const b=x.before;exact(b.node,'sha256 fileName');hash(b.node.sha256);assert.equal(b.node.fileName.toLowerCase(),'node.exe');exact(b.npm,'entry declaredVersion files');assert.equal(b.npm.entry,'bin/npm-cli.js');assert(/^[0-9]+\.[0-9]+\.[0-9]+$/.test(b.npm.declaredVersion));assert.equal(x.npmRuntimeVersion,b.npm.declaredVersion);exact(b.powershell,'version edition hostSha256 files');assert.equal(b.powershell.edition,'Core');assert(/^[0-9A-Za-z.+-]{1,100}$/.test(b.powershell.version));hash(b.powershell.hostSha256);for(const tree of [b.npm.files,b.powershell.files]){assert(Object.keys(tree).length>0&&Object.keys(tree).length<=20000);for(const [k,v]of Object.entries(tree)){safePath(k);hash(v);}}assert(b.npm.files['bin/npm-cli.js']);
 exact(b.runtime,'framework osDescription osVersion processArchitecture osArchitecture imageOS imageVersion');assert(/^\.NET [0-9A-Za-z.+-]{1,100}$/.test(b.runtime.framework));assert(/^Microsoft Windows [0-9A-Za-z. ()_-]{1,150}$/.test(b.runtime.osDescription));assert(/^[0-9.]{1,50}$/.test(b.runtime.osVersion));assert.equal(b.runtime.processArchitecture,'X64');assert.equal(b.runtime.osArchitecture,'X64');for(const k of ['imageOS','imageVersion'])assert(/^[A-Za-z0-9._-]{1,100}$/.test(b.runtime[k]));exact(x.nodeRuntime,'version arch');assert.equal(x.nodeRuntime.version,'v24.21.0');assert.equal(x.nodeRuntime.arch,'x64');assert.deepEqual(x.compiler.map(r=>r.name).sort(),['Microsoft.CodeAnalysis','Microsoft.CodeAnalysis.CSharp','System.Private.CoreLib']);for(const r of x.compiler){exact(r,'name version relativePath sha256');assert(/^[0-9.]{1,50}$/.test(r.version));safePath(r.relativePath);hash(r.sha256);assert.equal(b.powershell.files[r.relativePath],r.sha256);}}
export function validate(root,expected){let total=0;const names=readdirSync(root),parsed={},texts={};assert(names.includes('setup-summary.json'));for(const name of names){assert(files.has(name));const path=join(root,name),st=lstatSync(path);assert(st.isFile()&&!st.isSymbolicLink());assert(st.size<=(name==='dependency-result.json'?16777216:name==='tool-provenance.json'?8388608:1048576));total+=st.size;assert(total<=25165824);const data=readFileSync(path,'utf8');texts[name]=data;if(name.endsWith('.tap')){tap(data,name==='controls.tap'?expected:policyNames);continue;}const x=JSON.parse(data);parsed[name]=x;
 if(name==='setup-summary.json'){exact(x,'stage outcome errorHResult behavioralInvocations nodeSha256 platform nodeVersion logs rawFailureOutputUploaded qualification');assert(['provenance','native-controls','dependency-install','dependency-acceptance','final-packet-guards','setup-complete'].includes(x.stage));assert(['PASS','FAILED'].includes(x.outcome));assert.equal(x.behavioralInvocations,0);assert.equal(x.platform,'win32');assert.equal(x.nodeVersion,'24.21.0');assert.equal(x.rawFailureOutputUploaded,false);assert(Number.isInteger(x.errorHResult));hash(x.nodeSha256);assert(x.logs.length<=3);assert.equal(new Set(x.logs.map(l=>l.name)).size,x.logs.length);for(const l of x.logs){exact(l,'name bytes sha256');assert(['adapter-install.log','pi-install.log','acceptance.log'].includes(l.name));integer(l.bytes);assert(l.bytes<=8388608);hash(l.sha256);}assert.equal(x.qualification,'Setup-only. Failed setup output may be incomplete; no Windows behavioral or historical cause acceptance.');}
 else if(name==='native-native-result.json'){exact(x,'stage outcome syntheticCases exactControls behavioralInvocations qualification');assert.equal(x.stage,'native-setup');assert.equal(x.outcome,'PASS');assert.equal(x.syntheticCases,8);assert.equal(x.exactControls,46);assert.equal(x.behavioralInvocations,0);assert.equal(x.qualification,'Native setup only; no real adapter/Pi/model or historical Windows failure observation.');}
 else if(name==='dependency-result.json')dep(x);
 else if(name==='tool-provenance.json')tools(x);
 else if(name==='resolution-control-result.json'){exact(x,'outcome cases importCondition requireCondition entryExecution');assert.equal(x.outcome,'PASS');assert.equal(x.cases,1);assert.equal(x.importCondition,'import.mjs');assert.equal(x.requireCondition,'require.cjs');assert.equal(x.entryExecution,false);}
 else if(name==='latch-result.json'){assert.equal(x.length,8);assert.deepEqual(x.map(r=>r.name),latchNames);for(let i=0;i<x.length;i++){exact(x[i],'name nextLaunchPermitted expected outcome actualChildLaunches');assert.equal(x[i].nextLaunchPermitted,i<3);assert.equal(x[i].expected,i<3);assert.equal(x[i].outcome,'PASS');assert.equal(x[i].actualChildLaunches,0);}}
 else if(['acceptance-receipt.json','policy-receipt.json','resolution-receipt.json'].includes(name))receipt(x);
 else {const rows=Array.isArray(x)?x:[x];parsed[name]=rows;assert(rows.length<=9);assert.equal(new Set(rows.map(r=>r.name)).size,rows.length);for(const row of rows){exact(row,'name receipt');assert([...nativeNames,'adapter-install','pi-install','node-version','npm-version'].includes(row.name));receipt(row.receipt);}}
 }
 const summary=parsed['setup-summary.json'];if(summary.outcome==='PASS'){
 assert.equal(expected.length,46);assert.equal(new Set(expected).size,46);assert.equal(policyNames.length,26);assert.equal(new Set(policyNames).size,26);assert.equal(summary.stage,'setup-complete');assert.equal(summary.errorHResult,0);assert.deepEqual(names.sort(),[...files].sort());
 const rows=parsed['native-native-receipts.json'];assert.deepEqual(rows.map(r=>r.name),nativeNames);
 for(const row of rows){const r=row.receipt;if(row.name==='assignment-refusal-unresumed'){assert.equal(r.reason,'assignment_failed');assert(!r.assigned&&!r.resumed&&r.rootSignalled);assert.deepEqual(r.interventions,['terminate_unresumed_process_handle']);continue;}assert(r.assigned&&r.resumed&&r.activeZero&&r.rootSignalled&&r.readerDone&&!r.readerError);
 if(row.name==='original-nonzero'){assert.equal(r.reason,'completed');assert.equal(r.originalExit,7);assert(!r.overflow);assert.deepEqual(r.interventions,[]);}
 else if(['deadline-disposal','grandchild-disposal','retired-parent-disposal'].includes(row.name)){assert.equal(r.reason,'deadline');assert(!r.overflow);assert.deepEqual(r.interventions,['terminate_owned_job']);if(row.name==='grandchild-disposal')assert(r.maximumActive>=3);if(row.name==='retired-parent-disposal'){assert(r.maximumActive>=2);assert.equal(r.originalExit,0);}}
 else if(row.name==='stream-cap'){assert.equal(r.reason,'output_cap');assert(r.overflow&&r.written<=8192&&r.read<=12288);}
 else success(r);}
 for(const [file,ordered]of [['install-receipts.json',['adapter-install','pi-install']],['version-receipts.json',['node-version','npm-version']]]){assert.deepEqual(parsed[file].map(r=>r.name),ordered);parsed[file].forEach(r=>success(r.receipt));}
 for(const file of ['acceptance-receipt.json','policy-receipt.json','resolution-receipt.json'])success(parsed[file]);
 assert.equal(parsed['tool-provenance.json'].before.node.sha256,summary.nodeSha256);
 assert.deepEqual(summary.logs.map(l=>l.name),['adapter-install.log','pi-install.log','acceptance.log']);
 for(const [name,r]of [['adapter-install.log',parsed['install-receipts.json'][0].receipt],['pi-install.log',parsed['install-receipts.json'][1].receipt],['acceptance.log',parsed['acceptance-receipt.json']]])assert.equal(summary.logs.find(l=>l.name===name).bytes,r.written);
 }else assert.notEqual(summary.stage,'setup-complete');
 return {files:names.length,bytes:total,outcome:summary.outcome};}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){assert.equal(process.argv.length,4);const expected=JSON.parse(readFileSync(process.argv[3],'utf8'));validate(resolve(process.argv[2]),expected);}
