//! Protocol v2.0 method catalog — frozen wire-contract constants.
//!
//! This module enumerates the complete JSON-RPC surface frozen as protocol v2.0.
//! Every client-callable method, alias, notification, and reverse RPC is cataloged
//! here. The golden test (`catalog/tests.rs`) enforces that any surface drift
//! (added/removed/renamed methods) fails CI with a clear "update the catalog +
//! docs/protocol/ + bump protocol version" message.

#[cfg(test)]
mod tests;

/// Router methods (canonical, dispatched via `router::dispatch`).
///
/// These are the 300 canonical methods routed through the main dispatch match in
/// `router.rs` (aliases are listed separately in `METHOD_ALIASES`; the dispatch
/// arms match both canonical and alias spellings). Every method here is guaranteed
/// to return `-32601 Method not found` when the method name is unknown, or a domain
/// error code (never `-32601`) when the method is recognized but fails for other reasons.
#[cfg(test)]
pub(crate) const ROUTER_METHODS: &[&str] = &[
    "agent.appendMessage",
    "agent.cancelDelete",
    "agent.cancelSubscriptions",
    "agent.completeOnce",
    "agent.create",
    "agent.delegate",
    "agent.delete",
    "agent.diagnostics",
    "agent.dismissQuestions",
    "agent.editAndRegenerate",
    "agent.editQueuedMessage",
    "agent.enhancePrompt",
    "agent.get",
    "agent.getConversation",
    "agent.getMessageBlock",
    "agent.getModels",
    "agent.getQueue",
    "agent.getSession",
    "agent.getSessionStats",
    "agent.getSubscriptions",
    "agent.list",
    "agent.listActive",
    "agent.listInterrupted",
    "agent.listUserMessages",
    "agent.markSeen",
    "agent.pendingPermissions",
    "agent.queueMessage",
    "agent.removeQueuedMessage",
    "agent.rename",
    "agent.replaceMessages",
    "agent.reportToParent",
    "agent.resolveInterrupted",
    "agent.resolveProposal",
    "agent.respondPermission",
    "agent.restore",
    "agent.retry",
    "agent.sendMessage",
    "agent.sendQueuedMessageNow",
    "agent.sendToTask",
    "agent.setModel",
    "agent.stop",
    "agent.subscribe",
    "agent.summary",
    "agent.unsubscribe",
    "agent.update",
    "agent.wakeOrCreate",
    "comment.add",
    "comment.delete",
    "comment.getThread",
    "comment.list",
    "comment.resolveThread",
    "comment.respond",
    "crossWorkspace.listNotes",
    "crossWorkspace.listSiblings",
    "crossWorkspace.readNote",
    "debug.sampleStacks",
    "event.agentActivity",
    "event.query",
    "event.workspaceSummary",
    "file.attachmentUpload.abort",
    "file.attachmentUpload.begin",
    "file.attachmentUpload.chunk",
    "file.attachmentUpload.commit",
    "file.delete",
    "file.exists",
    "file.getAttachmentInfo",
    "file.list",
    "file.mkdir",
    "file.placeAttachment",
    "file.read",
    "file.readChunk",
    "file.rename",
    "file.stat",
    "file.tree",
    "file.write",
    "git.agentCommit",
    "git.branchDiff",
    "git.branchStatus",
    "git.changes",
    "git.checkMergeConflicts",
    "git.checkoutBranch",
    "git.clone",
    "git.commit",
    "git.commitDetails",
    "git.commits",
    "git.createBranch",
    "git.diffs",
    "git.discard",
    "git.fetch",
    "git.getBranches",
    "git.getConfig",
    "git.getRemoteUrl",
    "git.numstat",
    "git.pull",
    "git.push",
    "git.removeLockFile",
    "git.renameBranch",
    "git.showFile",
    "git.stage",
    "git.stageHunk",
    "git.status",
    "git.unstage",
    "git.unstageHunk",
    "gitRoot.list",
    "github.authStatus",
    "github.branches.list",
    "github.branches.listCached",
    "github.cancelAuth",
    "github.connect",
    "github.getReviewThreads",
    "github.getUser",
    "github.issues.get",
    "github.issues.list",
    "github.issues.search",
    "github.listReviewComments",
    "github.pulls.create",
    "github.pulls.get",
    "github.pulls.list",
    "github.pulls.merge",
    "github.pulls.search",
    "github.pulls.updateBranch",
    "github.replyReviewComment",
    "github.repoConfig.get",
    "github.repos.get",
    "github.repos.list",
    "github.repos.search",
    "github.resolveThread",
    "github.revoke",
    "github.unresolveThread",
    "hook.cancel",
    "hook.list",
    "hook.runNow",
    "linear.authStatus",
    "linear.createIssue",
    "linear.getIssue",
    "linear.listIssues",
    "linear.listLabels",
    "linear.listProjects",
    "linear.listTeams",
    "linear.listWorkflowStates",
    "linear.searchIssues",
    "linear.updateIssue",
    "linear.viewer",
    "mcp.oauth.delete",
    "mcp.oauth.get",
    "mcp.oauth.list",
    "mcp.oauth.set",
    "mcp.servers.create",
    "mcp.servers.delete",
    "mcp.servers.getStatus",
    "mcp.servers.list",
    "mcp.servers.restart",
    "mcp.servers.toggle",
    "mcp.servers.update",
    "mcp.testConnection",
    "metrics.clearAgentStats",
    "metrics.getAgentStats",
    "metrics.getAllWorkspaceStats",
    "metrics.getWorkspaceStats",
    "models.list",
    "note.add",
    "note.create",
    "note.delete",
    "note.edit",
    "note.editLines",
    "note.get",
    "note.getVersion",
    "note.lineAttribution.computeNow",
    "note.lineAttribution.load",
    "note.list",
    "note.listTasks",
    "note.listVersions",
    "note.readAsset",
    "note.restoreVersion",
    "note.saveAsset",
    "note.setContent",
    "note.update",
    "note.updateMetadata",
    "pr.refresh",
    "pr.status",
    "prMonitor.cancel",
    "prMonitor.flush",
    "prMonitor.list",
    "primitive.addAgentAction",
    "primitive.addCli",
    "primitive.addPatch",
    "primitive.addReference",
    "providers.catalog",
    "repo.list",
    "repo.remove",
    "repo.warmCache",
    "repoConfig.ensureDir",
    "repoConfig.get",
    "repoConfig.has",
    "repoConfig.save",
    "rules.get",
    "rules.list",
    "rules.update",
    "sandbox.cow.discard",
    "sandbox.cow.merge",
    "script.create",
    "script.list",
    "script.output",
    "script.remove",
    "script.restart",
    "script.run",
    "script.start",
    "script.status",
    "script.stop",
    "search.cancel",
    "search.codebase",
    "search.events",
    "search.fileNames",
    "search.inFiles",
    "search.messages",
    "search.notes",
    "sentry.assignIssue",
    "sentry.authStatus",
    "sentry.getIssue",
    "sentry.ignoreIssue",
    "sentry.listIssues",
    "sentry.listProjects",
    "sentry.resolveIssue",
    "sentry.searchIssues",
    "settings.get",
    "settings.list",
    "settings.reset",
    "settings.update",
    "skill.list",
    "specialist.create",
    "specialist.delete",
    "specialist.edit",
    "specialist.get",
    "specialist.list",
    "stats.getRateHistory",
    "stats.getUsage",
    "system.capabilities",
    "task.assignAgent",
    "task.convertBlocks",
    "task.createPrerequisite",
    "task.get",
    "task.getMyTask",
    "task.linkAgent",
    "task.list",
    "task.listAgentLinks",
    "task.markAsTask",
    "task.removeAgentFromAllTasks",
    "task.setRelations",
    "task.unlinkAgent",
    "task.update",
    "task.updateNoteStatus",
    "task.updateStatus",
    "terminal.create",
    "terminal.getBuffer",
    "terminal.kill",
    "terminal.list",
    "terminal.readOutput",
    "terminal.resize",
    "terminal.write",
    "unsloth.status",
    "unsloth.stop",
    "voice.getWorkspaceVocabulary",
    "voice.transcribe",
    "workspace.archive",
    "workspace.cancelDelete",
    "workspace.cleanup",
    "workspace.create",
    "workspace.delete",
    "workspace.detectProjectType",
    "workspace.diskUsage",
    "workspace.dismissAttention",
    "workspace.duplicate",
    "workspace.export.abort",
    "workspace.export.finalize",
    "workspace.export.read",
    "workspace.export.start",
    "workspace.findRepositories",
    "workspace.generateSetupScript",
    "workspace.get",
    "workspace.getAutoCommit",
    "workspace.getContext",
    "workspace.getSetupScript",
    "workspace.getTokenUsage",
    "workspace.getUiContext",
    "workspace.import.abort",
    "workspace.import.begin",
    "workspace.import.chunk",
    "workspace.import.commit",
    "workspace.initializeRepository",
    "workspace.list",
    "workspace.localChanges",
    "workspace.markSeen",
    "workspace.restore",
    "workspace.saveSetupScript",
    "workspace.setAutoCommit",
    "workspace.transfer.plan",
    "workspace.unarchive",
    "workspace.update",
    "workspace.updateContext",
    "workspace.updateUiContext",
];

/// Method aliases (wire-accepted → canonical).
///
/// The daemon accepts these 2 alias forms and dispatches them to their canonical
/// counterparts. The wire accepts both, but the canonical name is the documented
/// form in docs/protocol/05-method-catalog.md.
#[cfg(test)]
pub(crate) const METHOD_ALIASES: &[(&str, &str)] =
    &[("git.diff", "git.diffs"), ("git.log", "git.commits")];

/// Fast-path methods (intercepted before `router::dispatch`).
///
/// These 39 methods are handled by dedicated fast-path modules (`events.rs`,
/// `client.rs`, `drafts.rs`, `browser.rs`, `forward.rs`, `host.rs`, `control.rs`,
/// `pairing.rs`, `server.rs`) before reaching the main router. They share the same JSON-RPC
/// envelope validation but are dispatched earlier in the connection task for
/// performance or to access per-connection state (e.g., `client_id` binding for
/// drafts).
#[cfg(test)]
pub(crate) const FASTPATH_METHODS: &[&str] = &[
    "browser.exec",
    "client.hello",
    "drafts.clear",
    "drafts.get",
    "drafts.set",
    "events.subscribe",
    "events.unsubscribe",
    "forward.close",
    "forward.create",
    "forward.list",
    "host.checkAuggie",
    "host.checkGh",
    "host.checkGit",
    "host.checkNode",
    "host.createDirectory",
    "host.directoryStatus",
    "host.env",
    "host.exec",
    "host.execStream",
    "host.execStream.cancel",
    "host.execStream.write",
    "host.findApp",
    "host.findBinary",
    "host.listDirectory",
    "host.listInstalledEditors",
    "host.openInEditor",
    "host.providerAuthStatus",
    "host.providerDiscovery",
    "host.providerTestPrompt",
    "host.status",
    "host.toolAvailability",
    "pairing.getInfo",
    "providers.setup.cancel",
    "providers.setup.login",
    "providers.setup.start",
    "providers.setup.status",
    "server.pairingInfo",
    "server.rotateToken",
    "system.gitCredential",
    "system.importLegacy",
    "system.requestUpdate",
    "system.shutdown",
    "system.status",
];

/// Server→client notifications.
///
/// These are unsolicited notifications sent from the daemon to connected clients
/// (no request `id`). `events.event` is the sole notification in protocol v2.0.
#[cfg(test)]
pub(crate) const NOTIFICATIONS: &[&str] = &["events.event"];

/// Client-served reverse RPCs (dispatched with `id: "rev-<n>"`).
///
/// These methods are client-callable triggers whose real work happens on the
/// connected frontend. The daemon validates the envelope, then dispatches a
/// reverse RPC back to the client with a synthetic `rev-<n>` request id and
/// echoes the client's result back to the original caller.
#[cfg(test)]
pub(crate) const REVERSE_METHODS: &[&str] = &[
    "browser.exec",
    "host.openExternal",
    "host.openInEditor",
    "host.pickApplication",
    "providers.setup.openLogin",
];
