//! Unit-style integration coverage for `intent-core::ids`.
//!
//! The id newtypes are generated by the `id_newtype!` macro, so the macro
//! expands to a separate copy for `WorkspaceId`/`NoteId`/`AgentId`/`ClientId`.
//! Each constructor / trait impl is exercised on every type so the macro
//! arms all show up as covered.

use std::collections::HashSet;
use std::str::FromStr;

use intent_core::ids::{AgentId, ClientId, NoteId, WorkspaceId};

fn assert_uuid_v4_shape(s: &str) {
    // `Uuid::new_v4().to_string()` is 36 chars with dashes at the canonical
    // positions (8-4-4-4-12).
    assert_eq!(s.len(), 36, "expected 36-char uuid, got {s:?}");
    let bytes = s.as_bytes();
    for &i in &[8usize, 13, 18, 23] {
        assert_eq!(bytes[i], b'-', "missing dash at position {i} in {s:?}");
    }
}

#[test]
fn new_generates_fresh_uuid_v4() {
    let a = WorkspaceId::new();
    let b = WorkspaceId::new();
    assert_ne!(a, b, "freshly minted ids must differ");
    assert_uuid_v4_shape(a.as_str());
    assert_uuid_v4_shape(NoteId::new().as_str());
    assert_uuid_v4_shape(AgentId::new().as_str());
    assert_uuid_v4_shape(ClientId::new().as_str());
}

#[test]
fn default_uses_new() {
    let a: WorkspaceId = WorkspaceId::default();
    assert_uuid_v4_shape(a.as_str());
    let b: NoteId = NoteId::default();
    assert_uuid_v4_shape(b.as_str());
    let c: AgentId = AgentId::default();
    assert_uuid_v4_shape(c.as_str());
    let d: ClientId = ClientId::default();
    assert_uuid_v4_shape(d.as_str());
}

#[test]
fn from_string_and_as_str_round_trip() {
    let raw = "ws-fixed".to_string();
    let w = WorkspaceId::from_string(raw.clone());
    assert_eq!(w.as_str(), raw);
    let n = NoteId::from_string("note-1");
    assert_eq!(n.as_str(), "note-1");
    let a = AgentId::from_string("agent-α");
    assert_eq!(a.as_str(), "agent-α");
    let c = ClientId::from_string(String::from("client-1"));
    assert_eq!(c.as_str(), "client-1");
}

#[test]
fn display_matches_inner_string() {
    let w = WorkspaceId::from_string("ws-1");
    assert_eq!(format!("{w}"), "ws-1");
    let n = NoteId::from_string("note-1");
    assert_eq!(n.to_string(), "note-1");
    let a = AgentId::from_string("agent-1");
    assert_eq!(format!("{a}"), "agent-1");
    let c = ClientId::from_string("client-1");
    assert_eq!(c.to_string(), "client-1");
}

#[test]
fn from_str_is_infallible_and_preserves_value() {
    let w: WorkspaceId = "ws-fixed".parse().expect("Infallible");
    assert_eq!(w.as_str(), "ws-fixed");
    let n = NoteId::from_str("note-1").expect("Infallible");
    assert_eq!(n.as_str(), "note-1");
    let a = AgentId::from_str("agent-1").expect("Infallible");
    assert_eq!(a.as_str(), "agent-1");
    let c = ClientId::from_str("client-1").expect("Infallible");
    assert_eq!(c.as_str(), "client-1");
}

#[test]
fn from_string_and_from_str_conversions() {
    // `From<String>`
    let w: WorkspaceId = "ws-1".to_string().into();
    assert_eq!(w.as_str(), "ws-1");
    let n: NoteId = String::from("note-1").into();
    assert_eq!(n.as_str(), "note-1");
    let a: AgentId = String::from("agent-1").into();
    assert_eq!(a.as_str(), "agent-1");
    let c: ClientId = String::from("client-1").into();
    assert_eq!(c.as_str(), "client-1");

    // `From<&str>`
    let w: WorkspaceId = "ws-2".into();
    assert_eq!(w.as_str(), "ws-2");
    let n: NoteId = "note-2".into();
    assert_eq!(n.as_str(), "note-2");
    let a: AgentId = "agent-2".into();
    assert_eq!(a.as_str(), "agent-2");
    let c: ClientId = "client-2".into();
    assert_eq!(c.as_str(), "client-2");
}

#[test]
fn ids_are_hashable_and_clone_equal() {
    let a = AgentId::from_string("agent-1");
    let b = a.clone();
    assert_eq!(a, b);
    let mut set: HashSet<AgentId> = HashSet::new();
    set.insert(a.clone());
    set.insert(b);
    assert_eq!(set.len(), 1, "Clone+Eq+Hash must be consistent");
    set.insert(AgentId::from_string("agent-2"));
    assert_eq!(set.len(), 2);
}

#[test]
fn serde_transparent_round_trip() {
    // `#[serde(transparent)]` means the id serializes as a bare string.
    let id = NoteId::from_string("note-Z");
    let json = serde_json::to_string(&id).unwrap();
    assert_eq!(json, "\"note-Z\"");
    let back: NoteId = serde_json::from_str(&json).unwrap();
    assert_eq!(back, id);

    // Each id type uses the same transparent representation.
    assert_eq!(
        serde_json::to_string(&WorkspaceId::from_string("ws-Z")).unwrap(),
        "\"ws-Z\""
    );
    assert_eq!(
        serde_json::to_string(&AgentId::from_string("agent-Z")).unwrap(),
        "\"agent-Z\""
    );
    assert_eq!(
        serde_json::to_string(&ClientId::from_string("client-Z")).unwrap(),
        "\"client-Z\""
    );
}
