#!/usr/bin/env python3
"""Required CI Rust test steps must match the local wrapper's caller policy.

Reads real YAML (PyYAML, already installed in release-scripts). The command
scan covers current bare and rustup-run test commands, not echoed plans or
command-substitution discovery lists. Current indirect routes have explicit
registration plus actual stub-child probes below, not a general shell parser.
Mutation tests ensure removed/disabled step policy and missing wiring fail.
"""

import copy
import json
import os
from pathlib import Path
import re
import shlex
import subprocess
import sys
import tempfile
import unittest

import yaml


ROOT = Path(__file__).resolve().parent.parent
JOBS = ("check", "build", "coverage-e2e", "coverage-all", "coverage-changed")
# These required steps launch through Python or a Bash array; scanning shell
# command prefixes cannot discover their runtime children. Execute their real
# workflow bodies with a stub rustup in test_indirect_workflow_child_environments.
INDIRECT_TEST_STEPS = {
    ("build", "Tunnel deadline and TLS controls (macOS runtime)"),
    ("build", "Retained workspace CoW fixtures (macOS runtime)"),
}
COMMAND = re.compile(
    r"^(?:[A-Z_]+=\S+\s+)*(?:(?:rustup\s+run\s+\S+\s+)?cargo\s+(?:test\b|nextest\s+run\b|llvm-cov\b[^\n]*\bnextest\b)"
    r"|\./scripts/(?:coverage-e2e|coverage-all|changed-tests)\.sh\b)"
)


def test_steps(workflow):
    for name in JOBS:
        job = workflow["jobs"][name]
        for step in job["steps"]:
            run = str(step.get("run", ""))
            if (name, step.get("name")) in INDIRECT_TEST_STEPS or any(COMMAND.search(line.strip()) and "--dry-run" not in line for line in run.splitlines()):
                yield name, job, step


def violations(workflow, policy):
    errors = []
    found = set()
    for name, job, step in test_steps(workflow):
        found.add(name)
        env = {**workflow.get("env", {}), **job.get("env", {}), **step.get("env", {})}
        command_policies = [str(env.get("INTENTD_ASSERT_BOUND_CALLER", ""))]
        # A step-wide unset previously disabled every retained CoW fixture.
        if re.search(r"^\s*unset\b[^\n]*\bINTENTD_ASSERT_BOUND_CALLER\b", str(step.get("run", "")), re.M):
            command_policies.append("")
        for line in str(step.get("run", "")).splitlines():
            if COMMAND.search(line.strip()) and "--dry-run" not in line:
                command_env = dict(env)
                # Leading shell assignments take precedence over the YAML env.
                prefix = re.match(r"^(?:[A-Z_]+=\S+\s+)*", line.strip()).group()
                for assignment in shlex.split(prefix):
                    key, value = assignment.split("=", 1)
                    command_env[key] = value
                command_policies.append(str(command_env.get("INTENTD_ASSERT_BOUND_CALLER", "")))
        if any(value != policy for value in command_policies):
            errors.append(f"{name}: {step.get('name')} must arm INTENTD_ASSERT_BOUND_CALLER={policy}")
        if job.get("continue-on-error") or step.get("continue-on-error"):
            errors.append(f"{name}: test policy must remain required")
    if found != set(JOBS):
        errors.append(f"missing test jobs: {set(JOBS) - found}")
    source_lints = workflow["jobs"]["check"]["steps"]
    if not any(step.get("run") == "cargo test --workspace --test '*_lint'" for step in source_lints):
        errors.append("source lint discovery must retain its literal glob invocation")
    gate = workflow["jobs"]["gate"]
    if not set((*JOBS, "release-scripts")).issubset(gate["needs"]):
        errors.append("CI Gate must require test jobs and policy regressions")
    steps = workflow["jobs"]["release-scripts"]["steps"]
    for script in ("test-test-policy.py", "test-ci-test-policy.py"):
        matches = [step for step in steps if re.search(r"^python3 (?:-[IBS] )*scripts/" + re.escape(script) + r"$", str(step.get("run", "")), re.M)]
        if not matches or any(step.get("if") or step.get("continue-on-error") for step in matches):
            errors.append(f"release-scripts must run {script} unconditionally")
    return errors


# Independently audited from ci.yml, not generated by test_steps/COMMAND. Keep
# this inventory explicit so scanner omissions cannot also erase mutations.
REQUIRED_TEST_STEPS = {
    ("check", "Real import and public session contract"): 1,
    ("check", "Source lints"): 1,
    ("check", "GitLab auth, invitations and checkout over real sockets with explicit test transports"): 1,
    ("check", "Coverage-skipped tests (STAB-40/43)"): 2,
    ("check", "Installer guard tests (install_ps1_owner)"): 1,
    # None: indirect Python/Bash-array routes are executed with a stub below.
    ("build", "Tunnel deadline and TLS controls (macOS runtime)"): None,
    ("build", "Retained workspace CoW fixtures (macOS runtime)"): None,
    ("build", "Headless workspace setup (Windows runtime)"): 1,
    ("build", "Codex diagnostic process ownership (Windows runtime)"): 1,
    ("build", "Codex focused diagnostics (macOS runtime)"): 2,
    ("coverage-e2e", "Run e2e coverage"): 1,
    ("coverage-all", "Run combined coverage"): 1,
    ("coverage-changed", "Run changed tests under llvm-cov"): 1,
    ("coverage-changed", "Run callback fixture composition under llvm-cov"): 1,
}


class CiPolicyTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.workflow = yaml.safe_load((ROOT / ".github/workflows/ci.yml").read_text())

    def test_required_ci_matches_wrapper(self):
        result = subprocess.run(
            ["bash", str(ROOT / "scripts/with-test-policy.sh"), "sh", "-c", 'printf "%s" "$INTENTD_ASSERT_BOUND_CALLER"'],
            env={**os.environ, "INTENTD_ASSERT_BOUND_CALLER": "0"}, capture_output=True, text=True, timeout=5,
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(result.stdout, "1")
        self.assertEqual(violations(self.workflow, result.stdout), [])

    def test_each_required_test_step_rejects_missing_or_disabled_policy(self):
        for name, step_name in REQUIRED_TEST_STEPS:
            for value in (None, "0", "false"):
                with self.subTest(job=name, step=step_name, value=value):
                    workflow = copy.deepcopy(self.workflow)
                    mutated = next(s for s in workflow["jobs"][name]["steps"] if s.get("name") == step_name)
                    env = mutated.setdefault("env", {})
                    if value is None:
                        env.pop("INTENTD_ASSERT_BOUND_CALLER", None)
                    else:
                        env["INTENTD_ASSERT_BOUND_CALLER"] = value
                    self.assertIn(
                        f"{name}: {step_name} must arm INTENTD_ASSERT_BOUND_CALLER=1",
                        violations(workflow, "1"),
                    )

    def test_discovery_matches_independent_required_step_inventory(self):
        discovered = {}
        for name, _, step in test_steps(self.workflow):
            discovered[(name, step["name"])] = sum(
                bool(COMMAND.search(line.strip())) and "--dry-run" not in line
                for line in step["run"].splitlines()
            ) or None
        self.assertEqual(discovered, REQUIRED_TEST_STEPS)

    def test_indirect_route_cannot_unset_policy(self):
        for step_name in ("Tunnel deadline and TLS controls (macOS runtime)",
                          "Retained workspace CoW fixtures (macOS runtime)"):
            with self.subTest(step=step_name):
                workflow = copy.deepcopy(self.workflow)
                step = next(s for s in workflow['jobs']['build']['steps'] if s.get('name') == step_name)
                step['run'] = 'unset INTENTD_ASSERT_BOUND_CALLER\n' + step['run']
                self.assertIn(f"build: {step_name} must arm INTENTD_ASSERT_BOUND_CALLER=1", violations(workflow, "1"))

    def test_indirect_workflow_child_environments(self):
        for step_name, expected_tests in (
            ("Tunnel deadline and TLS controls (macOS runtime)", 8),
            ("Retained workspace CoW fixtures (macOS runtime)", 6),
        ):
            with self.subTest(step=step_name), tempfile.TemporaryDirectory() as tmp:
                root = Path(tmp)
                stub = root / "rustup"
                stub.write_text(
                    f"#!{sys.executable} -S\n"
                    "import json,os,sys\n"
                    "args=sys.argv[1:]\n"
                    "with open(os.environ['POLICY_CHILD_LOG'],'a') as log:\n"
                    " log.write(json.dumps([args,os.environ.get('INTENTD_ASSERT_BOUND_CALLER')])+'\\n')\n"
                    "if '--no-run' in args: sys.exit(0)\n"
                    "test=args[args.index('--')-1]\n"
                    "if '--list' in args:\n"
                    " print(test+': test'); print('1 test, 0 benchmarks'); sys.exit(0)\n"
                    "print('running 1 test')\n"
                    "print('test result: ok. 1 passed; 0 failed; 0 ignored;')\n"
                    "print('CoW fixture clone and independent contents verified')\n"
                    "print('CoW fixture proof scratch cleaned')\n"
                    "print('CoW fixture assertions passed: '+test.split('::')[-1])\n"
                )
                stub.chmod(0o755)
                step = next(s for s in self.workflow['jobs']['build']['steps'] if s.get('name') == step_name)
                env = {**os.environ, 'INTENTD_ASSERT_BOUND_CALLER': '0', **step.get('env', {})}
                env = {k: re.sub(r'\$\{\{.*?\}\}', 'fixture', str(v)) for k, v in env.items()}
                env.update(PATH=str(root)+os.pathsep+os.environ['PATH'], RUNNER_TEMP=str(root), POLICY_CHILD_LOG=str(root/'children.jsonl'))
                run = step['run'].replace('${{ matrix.target }}', 'fixture')
                result = subprocess.run(['bash', '-e', '-o', 'pipefail', '-c', run], cwd=root, env=env, capture_output=True, text=True, timeout=10)
                self.assertEqual(result.returncode, 0, result.stdout+result.stderr)
                calls = [json.loads(line) for line in (root/'children.jsonl').read_text().splitlines()]
                runtime = [(args, policy) for args, policy in calls if '--nocapture' in args]
                self.assertEqual(len(runtime), expected_tests)
                for args, policy in runtime:
                    self.assertEqual(policy, '1', args)
                    self.assertIn('--exact', args)
                    self.assertIn('--test-threads=1', args)
                self.assertEqual(len([args for args, _ in calls if '--list' in args]), expected_tests)

    def test_rustup_runtime_commands_are_discovered(self):
        for command in (
            'rustup run "$INTENTD_DIAGNOSTIC_TOOLCHAIN" cargo test -p intent-services --lib',
            'INTENTD_ASSERT_BOUND_CALLER=0 rustup run stable cargo test -p intentd',
        ):
            with self.subTest(command=command):
                workflow = copy.deepcopy(self.workflow)
                workflow["jobs"]["build"]["steps"].append({
                    "name": "New platform tests", "run": command,
                })
                self.assertIn("build: New platform tests must arm INTENTD_ASSERT_BOUND_CALLER=1", violations(workflow, "1"))

    def test_unarmed_new_test_step_is_discovered(self):
        workflow = copy.deepcopy(self.workflow)
        workflow["jobs"]["check"]["steps"].append({"name": "New Rust tests", "run": "cargo test -p new-crate"})
        self.assertTrue(any("New Rust tests" in error for error in violations(workflow, "1")))

    def test_shell_assignment_cannot_disable_ci_policy(self):
        workflow = copy.deepcopy(self.workflow)
        workflow["jobs"]["check"]["steps"].append({
            "name": "Disabled Rust tests", "env": {"INTENTD_ASSERT_BOUND_CALLER": "1"},
            "run": "INTENTD_ASSERT_BOUND_CALLER=0 cargo test -p new-crate",
        })
        self.assertTrue(any("Disabled Rust tests" in error for error in violations(workflow, "1")))

    def test_missing_regression_wiring_is_rejected(self):
        for script in ("test-test-policy.py", "test-ci-test-policy.py"):
            workflow = copy.deepcopy(self.workflow)
            steps = workflow["jobs"]["release-scripts"]["steps"]
            workflow["jobs"]["release-scripts"]["steps"] = [s for s in steps if script not in s.get("run", "")]
            self.assertTrue(any(script in error for error in violations(workflow, "1")))


class CallbackDiscoveryTests(unittest.TestCase):
    """Execute the actual workflow shell; stub only Cargo and selection inputs."""

    @classmethod
    def setUpClass(cls):
        cls.workflow = yaml.safe_load((ROOT / ".github/workflows/ci.yml").read_text())
        cls.job = cls.workflow["jobs"]["coverage-changed"]
        cls.step = next(s for s in cls.job["steps"] if s.get("name") == "Run callback fixture composition under llvm-cov")

    def probe(self, *, target=None, coverage_target=None, listing="exact", failure=None, style="wrapper"):
        with tempfile.TemporaryDirectory(prefix="callback-discovery-") as tmp:
            root = Path(tmp)
            stub = root / "cargo"
            stub.write_text(f"#!{sys.executable} -S\n" + r'''import json, os, shlex, sys
args = sys.argv[1:]
keys = ["RUSTFLAGS", "RUSTC_WRAPPER", "CARGO_TARGET_DIR", "CARGO_LLVM_COV_TARGET_DIR",
        "CARGO_LLVM_COV_SHOW_ENV", "LLVM_PROFILE_FILE", "INTENTD_ASSERT_BOUND_CALLER",
        "INTENTD_TEST_TIMEOUT_MULTIPLIER", "__CARGO_LLVM_COV_RUSTC_WRAPPER"]
with open(os.environ["CHILD_LOG"], "a") as log:
    log.write(json.dumps({"args": args, "env": {k: os.environ.get(k) for k in keys}}) + "\n")
if args[0] == "metadata":
    print(json.dumps({"target_directory": os.environ.get("CARGO_TARGET_DIR", os.environ["RUNNER_TEMP"] + "/target")}))
elif args[:2] == ["llvm-cov", "show-env"]:
    if os.environ["FAILURE"] == "show-env": sys.exit(9)
    target = os.environ.get("CARGO_LLVM_COV_TARGET_DIR", os.environ.get("CARGO_TARGET_DIR", os.environ["RUNNER_TEMP"] + "/target"))
    exports = {"CARGO_LLVM_COV_TARGET_DIR": os.environ.get("CARGO_TARGET_DIR", os.environ["RUNNER_TEMP"] + "/target"), "CARGO_LLVM_COV_SHOW_ENV": "1", "LLVM_PROFILE_FILE": target + "/test.profraw"}
    if os.environ["STYLE"] == "wrapper":
        exports.update(RUSTC_WRAPPER="coverage-wrapper", __CARGO_LLVM_COV_RUSTC_WRAPPER="1")
    else:
        exports["RUSTFLAGS"] = os.environ.get("RUSTFLAGS", "") + " -C instrument-coverage --cfg=coverage"
    for key, value in exports.items(): print("export " + key + "=" + shlex.quote(value))
elif args[:2] == ["nextest", "list"]:
    if os.environ["FAILURE"] == "list": sys.exit(10)
    names = os.environ["CALLBACK_FIXTURE_TESTS"].split()
    mode = os.environ["LISTING"]
    if mode == "missing": names.pop()
    if mode == "extra": names.append("unexpected_test")
    if mode == "wrong": names[-1] = "wrong_test"
    if mode == "empty": names = []
    cases = {n: {"filter-match": {"status": "matches"}} for n in names}
    cases["unselected_test"] = {"filter-match": {"status": "mismatch"}}
    suites = {"unit": {"testcases": cases}}
    if mode == "duplicate": suites["duplicate"] = {"testcases": {names[0]: cases[names[0]]}}
    print(json.dumps({"rust-suites": suites}))
elif args[:3] == ["llvm-cov", "--no-report", "nextest"]:
    sys.exit(11 if os.environ["FAILURE"] == "run" else 0)
else:
    sys.exit("unexpected cargo invocation: " + str(args))
''')
            stub.chmod(0o755)
            env = {k: v for k, v in os.environ.items() if not k.startswith(("CARGO_", "RUST", "LLVM_", "__CARGO_"))}
            env.update({k: str(v) for k, v in self.job["env"].items()})
            env.update({k: str(v) for k, v in self.step["env"].items()})
            env.update(PATH=str(root) + os.pathsep + os.environ["PATH"], RUNNER_TEMP=tmp,
                       CHILD_LOG=str(root / "calls"), LISTING=listing, FAILURE=failure or "", STYLE=style,
                       RUSTFLAGS="--cfg=existing", RUSTC_WRAPPER="existing-wrapper")
            if target: env["CARGO_TARGET_DIR"] = str(root / target)
            if coverage_target: env["CARGO_LLVM_COV_TARGET_DIR"] = str(root / coverage_target)
            result = subprocess.run(["bash", "-e", "-o", "pipefail", "-c", self.step["run"]],
                                    env=env, cwd=root, capture_output=True, text=True, timeout=10)
            calls = [json.loads(line) for line in (root / "calls").read_text().splitlines()]
            expected_target = str(root / (coverage_target or ((target or "target") + "/llvm-cov-target")))
            return result, calls, expected_target

    def test_instrumented_discovery_reuses_execution_build_without_environment_leak(self):
        for target, override in ((None, None), ("slot target", None), ("slot target", "coverage override")):
            for style in ("wrapper", "flags"):
                with self.subTest(target=target, override=override, style=style):
                    result, calls, target_dir = self.probe(target=target, coverage_target=override, style=style)
                    self.assertEqual(result.returncode, 0, result.stderr)
                    listing = next(c for c in calls if c["args"][:2] == ["nextest", "list"])
                    run = next(c for c in calls if c["args"][:3] == ["llvm-cov", "--no-report", "nextest"])
                    self.assertEqual(listing["env"]["CARGO_LLVM_COV_SHOW_ENV"], "1")
                    self.assertEqual(listing["args"][listing["args"].index("--target-dir") + 1], target_dir)
                    self.assertEqual(run["env"]["CARGO_LLVM_COV_TARGET_DIR"], target_dir)
                    self.assertEqual(run["env"]["RUSTFLAGS"], "--cfg=existing")
                    self.assertEqual(run["env"]["RUSTC_WRAPPER"], "existing-wrapper")
                    for key in ("CARGO_LLVM_COV_SHOW_ENV", "LLVM_PROFILE_FILE", "__CARGO_LLVM_COV_RUSTC_WRAPPER"):
                        self.assertIsNone(run["env"][key], key)
                    if style == "wrapper":
                        self.assertEqual(listing["env"]["RUSTC_WRAPPER"], "coverage-wrapper")
                    else:
                        self.assertEqual(listing["env"]["RUSTFLAGS"].count("instrument-coverage"), 1)
                    for call in (listing, run):
                        args = call["args"]
                        self.assertEqual([args[i + 1] for i, arg in enumerate(args) if arg == "-p"], ["intent-acp", "intent-services"])
                        self.assertIn("--lib", args)
                        for flag in ("--release", "--cargo-profile", "--profile", "--features", "--all-features", "--no-default-features", "--target"):
                            self.assertNotIn(flag, args)
                        self.assertEqual(call["env"]["INTENTD_ASSERT_BOUND_CALLER"], "1")
                        self.assertEqual(call["env"]["INTENTD_TEST_TIMEOUT_MULTIPLIER"], "3")
                    self.assertEqual(listing["args"][listing["args"].index("-E") + 1], run["args"][run["args"].index("-E") + 1])
                    self.assertEqual(run["args"][run["args"].index("--retries") + 1], "0")
                    self.assertIn("--no-fail-fast", run["args"])

    def test_exact_selection_and_discovery_failures_prevent_execution(self):
        for mode in ("missing", "extra", "wrong", "empty", "duplicate"):
            with self.subTest(mode=mode):
                result, calls, _ = self.probe(listing=mode)
                self.assertNotEqual(result.returncode, 0)
                self.assertFalse(any(c["args"][:3] == ["llvm-cov", "--no-report", "nextest"] for c in calls))
        for failure, code in (("show-env", 9), ("list", 10), ("run", 11)):
            with self.subTest(failure=failure):
                result, calls, _ = self.probe(failure=failure)
                self.assertEqual(result.returncode, code, result.stderr)
                if failure != "run":
                    self.assertFalse(any(c["args"][:3] == ["llvm-cov", "--no-report", "nextest"] for c in calls))

    def test_callback_inventory_is_exact(self):
        self.assertEqual(self.job["env"]["CALLBACK_FIXTURE_TESTS"].split(), [
            "callback_registration::tests::actual_adapter_sdk_and_rust_mcp_deliver_distinct_callback_preserving_old_result",
            "callback_registration::tests::actual_adapter_replacement_rejects_old_query_and_disabled_never_registers",
            "agent_manager::repository_origin::callback_delivery::tests::live_context::confirmed_context_actual_created_3_1_reaches_original_guidance_boundary",
            "agent_manager::repository_origin::callback_delivery::tests::live_context::confirmed_context_saved_legacy_and_disabled_outbound_messages_remain_ordinary",
            "agent_manager::repository_origin::callback_delivery::tests::live_context::confirmed_context_load_and_failed_load_new_keep_original_producers_and_capture",
            "agent_manager::repository_origin::callback_delivery::tests::live_context::confirmed_context_successful_zero_pending_absent_and_failed_never_conflate",
        ])

    def test_callback_inventory_names_exist_in_source(self):
        sources = "\n".join((ROOT / path).read_text() for path in (
            "crates/intent-acp/src/callback_registration/tests.rs",
            "crates/intent-services/src/agent_manager/repository_origin/callback_delivery/tests.rs",
        ))
        for name in self.job["env"]["CALLBACK_FIXTURE_TESTS"].split():
            with self.subTest(test=name):
                self.assertIsNotNone(re.search(r"\bfn\s+" + re.escape(name.rsplit("::", 1)[-1]) + r"\s*\(", sources), name)

    def test_callback_selection_routing(self):
        select = next(s for s in self.job["steps"] if s.get("id") == "select")
        self.assertEqual(self.step["if"], "steps.select.outputs.callback_fixture_changed == 'true'")
        for fixture, changed in ((False, False), (True, False), (False, True), (True, True)):
            with self.subTest(fixture=fixture, changed=changed), tempfile.TemporaryDirectory() as tmp:
                root = Path(tmp)
                (root / "scripts").mkdir()
                script = root / "scripts/changed-tests.sh"
                script.write_text("#!/bin/sh\n" + ("echo 'cargo llvm-cov --no-report nextest -p other'\n" if changed else "echo 'No changed tests'\n"))
                script.chmod(0o755)
                git = root / "git"
                git.write_text("#!/bin/sh\nexit " + ("1" if fixture else "0") + "\n")
                git.chmod(0o755)
                env = {**os.environ, **{k: str(v) for k, v in self.job["env"].items()},
                       "PATH": str(root) + os.pathsep + os.environ["PATH"], "RUNNER_TEMP": tmp,
                       "GITHUB_OUTPUT": str(root / "output"), "GITHUB_STEP_SUMMARY": str(root / "summary"), "BASE_SHA": "base"}
                result = subprocess.run(["bash", "-e", "-o", "pipefail", "-c", select["run"]],
                                        env=env, cwd=root, capture_output=True, text=True, timeout=10)
                self.assertEqual(result.returncode, 0, result.stderr)
                self.assertEqual((root / "output").read_text().splitlines(),
                                 ["callback_fixture_changed=" + str(fixture).lower(), "has_selection=" + str(fixture or changed).lower()])


if __name__ == "__main__":
    unittest.main()
