//! Daemon-side auto-commit-on-idle subscriber (LNI-1, §5.6 / §9.1).
//!
//! Subscribes to `agent:idle` and, for normally-finished task-linked agents,
//! invokes [`crate::Services::git_agent_commit`] so the commit body carries the
//! `Agent-Id:` and `Linked-Note-Id:` trailers parsed by the history fast path.
//!
//! Skips silently (debug-level log) when the workspace has `git.autoCommit`
//! off (`assert_agent_commit_allowed` rejection), the worktree has no uncommitted
//! changes, the session opted out via `skip_auto_commit`, or the
//! `agent:idle` finish reason is non-normal (`error`/`cancelled`/
//! `provider_stopped`/`refusal`).

use intent_core::events::AGENT_IDLE;
use intent_core::{AgentId, AgentSession, Error, Event, NoteId, WorkspaceApi};

use crate::events::SubscriptionFilter;
use crate::Services;

/// Subject-line cap for auto-commit fallback messages (TS
/// `agent-commit.service.ts::buildCommitMessage`).
const SUBJECT_MAX_CHARS: usize = 72;
const DEFAULT_SUBJECT: &str = "Agent changes";
/// `assert_agent_commit_allowed` rejection text we treat as a silent skip
/// (must stay in sync with `git_ops::AUTO_COMMIT_DISABLED_MSG`).
const AUTO_COMMIT_DISABLED_MARK: &str = "Auto-commit is disabled";
/// `git_agent_commit` empty-worktree result (§5.6 parity) treated as a silent
/// skip — there is simply nothing to attribute to the idle agent.
const NO_CHANGES_MARK: &str = "No uncommitted changes found";
/// Clean-tree rejection from `intent_git::commit` when the worktree state
/// matches the parent commit exactly (also a benign skip).
const CLEAN_TREE_MARK: &str = "nothing to commit, working tree clean";

/// Whether the `agent:idle` `finishReason` is a normal turn-end we should
/// auto-commit on. Anything outside this allowlist (or missing) is treated as
/// a non-normal terminal state and skipped (TS
/// `handleAgentIdleAutoCommit` finish-reason gate).
fn is_normal_finish_reason(reason: Option<&str>) -> bool {
    matches!(
        reason,
        Some("end_turn" | "max_tokens" | "max_turn_requests" | "stream_complete")
    )
}

/// Whether an agent's display name was set explicitly by an `agent.rename` /
/// explicit-name caller (i.e., isn't the autogenerated `Agent xxxxxx` form).
/// Mirrors the TS `meaningfulAgentName` guard the auto-commit subject-line
/// fallback uses.
fn is_meaningful_agent_name(session: &AgentSession) -> bool {
    session.name_explicitly_set && !session.name.trim().is_empty()
}

/// Collapse whitespace runs (including embedded newlines) into single spaces,
/// trim, and clamp to [`SUBJECT_MAX_CHARS`] characters. Mirrors the TS
/// `buildCommitMessage` subject hygiene so trailers can be appended cleanly.
fn normalize_subject(raw: &str) -> String {
    let collapsed: String = raw.split_whitespace().collect::<Vec<_>>().join(" ");
    collapsed.chars().take(SUBJECT_MAX_CHARS).collect()
}

impl Services {
    /// Spawn the LNI-1 auto-commit worker: subscribe to `agent:idle` across
    /// every workspace and, for each normally-finished task-linked agent,
    /// invoke [`crate::Services::git_agent_commit`] so the commit carries the
    /// `Agent-Id:` and `Linked-Note-Id:` trailers. No-op-safe when no event
    /// bus is wired. Returns the task handle so the composition root can hold
    /// it for the process lifetime.
    pub fn spawn_auto_commit_loop(&self) -> tokio::task::JoinHandle<()> {
        let Some(bus) = self.event_bus.clone() else {
            tracing::info!("auto-commit-on-idle loop disabled: no event bus");
            return tokio::spawn(async {});
        };
        let services = self.clone();
        tokio::spawn(async move {
            // Span every workspace (workspace_id = None) and deliver each
            // matched event immediately (batch_window = None) so auto-commit
            // races no other turn-end work.
            let filter = SubscriptionFilter {
                event_types: vec![AGENT_IDLE.to_string()],
                ..Default::default()
            };
            let mut sub = bus.subscribe(filter);
            while let Some(events) = sub.recv().await {
                for event in events {
                    services.handle_agent_idle_auto_commit(&event).await;
                }
            }
        })
    }

    /// One-shot handler for a single `agent:idle` event. Logs and swallows
    /// every error so a single malformed event never tears down the worker.
    pub(crate) async fn handle_agent_idle_auto_commit(&self, event: &Event) {
        if event.event_type != AGENT_IDLE {
            return;
        }
        let Some(agent_id_str) = event.data.get("agentId").and_then(|v| v.as_str()) else {
            tracing::debug!("agent:idle missing agentId; skipping auto-commit");
            return;
        };
        let agent_id = AgentId::from(agent_id_str);
        let finish_reason = event.data.get("finishReason").and_then(|v| v.as_str());
        if !is_normal_finish_reason(finish_reason) {
            tracing::debug!(
                agent = %agent_id.0,
                reason = ?finish_reason,
                "auto-commit skipped: non-normal finishReason"
            );
            return;
        }
        // Load the idle session. A best-effort lookup: a missing session (e.g.,
        // racing delete) is not an auto-commit error — just log and skip.
        let session = match self.store().get_agent_session(&agent_id).await {
            Ok(s) => s,
            Err(e) => {
                tracing::debug!(
                    agent = %agent_id.0,
                    error = %e,
                    "auto-commit skipped: session lookup failed"
                );
                return;
            }
        };
        if session.skip_auto_commit {
            tracing::debug!(
                agent = %agent_id.0,
                "auto-commit skipped: session opted out via skipAutoCommit"
            );
            return;
        }
        let linked_note_id = session.task_note_id.clone();
        let subject = self
            .build_auto_commit_subject(&session, &linked_note_id)
            .await;
        match self
            .git_agent_commit(
                session.workspace_id.clone(),
                subject,
                Some(agent_id.clone()),
                linked_note_id.clone(),
                None,
                false,
            )
            .await
        {
            Ok(outcome) => {
                tracing::debug!(
                    agent = %agent_id.0,
                    workspace = %session.workspace_id.0,
                    hash = %outcome.hash,
                    files = outcome.file_count,
                    "auto-commit on agent idle"
                );
            }
            Err(Error::Internal(msg))
                if msg.contains(AUTO_COMMIT_DISABLED_MARK)
                    || msg.contains(NO_CHANGES_MARK)
                    || msg.contains(CLEAN_TREE_MARK) =>
            {
                tracing::debug!(
                    agent = %agent_id.0,
                    workspace = %session.workspace_id.0,
                    "auto-commit skipped: {msg}"
                );
            }
            Err(e) => {
                tracing::warn!(
                    agent = %agent_id.0,
                    workspace = %session.workspace_id.0,
                    error = %e,
                    "auto-commit failed"
                );
            }
        }
    }

    /// Resolve the auto-commit fallback subject (taskTitle → meaningful agent
    /// name → `"Agent changes"`), normalized to one line of ≤ 72 chars.
    pub(crate) async fn build_auto_commit_subject(
        &self,
        session: &AgentSession,
        linked_note_id: &Option<NoteId>,
    ) -> String {
        if let Some(note_id) = linked_note_id {
            if let Ok(note) = self.store().get_note(&session.workspace_id, note_id).await {
                let title = note.title.trim();
                if !title.is_empty() {
                    return normalize_subject(title);
                }
            }
        }
        if is_meaningful_agent_name(session) {
            return normalize_subject(&session.name);
        }
        DEFAULT_SUBJECT.to_string()
    }
}

#[cfg(test)]
mod tests;
