//! Daemon-side auto-commit-on-idle subscriber (LNI-1, §5.6 / §9.1).
//!
//! Subscribes to `agent:idle` and, for normally-finished task-linked agents,
//! invokes [`crate::Services::git_agent_commit`] so the commit body carries the
//! `Agent-Id:` and `Linked-Note-Id:` trailers parsed by the history fast path.
//!
//! Skips silently (debug-level log) when the workspace has `git.autoCommit`
//! off (`assert_agent_commit_allowed` rejection), the worktree has no uncommitted
//! changes, a merge is pending (scoped commits are refused mid-merge,
//! monorepo#4223), the session opted out via `skip_auto_commit`, or the
//! `agent:idle` finish reason is non-normal (`error`/`cancelled`/
//! `provider_stopped`/`refusal`).

use std::path::PathBuf;

use intent_core::events::AGENT_IDLE;
use intent_core::{AgentId, AgentSession, Error, Event, NoteId, WorkspaceApi};
use intent_git::commit::{CLEAN_TREE_ERROR, PARTIAL_MERGE_COMMIT_ERROR};

use crate::events::SubscriptionFilter;
use crate::instructions::get_instruction_with_common_for;
use crate::Services;

/// Subject-line cap for auto-commit fallback messages (TS
/// `agent-commit.service.ts::buildCommitMessage`).
const SUBJECT_MAX_CHARS: usize = 72;
const DEFAULT_SUBJECT: &str = "Agent changes";
/// `assert_agent_commit_allowed` rejection text we treat as a silent skip
/// (must stay in sync with `git_ops::AUTO_COMMIT_DISABLED_MSG`; pinned by
/// `git_ops::tests::disabled_rejection_matches_silent_skip_mark`).
pub(crate) const AUTO_COMMIT_DISABLED_MARK: &str = "Auto-commit is disabled";
/// `git_agent_commit` empty-worktree result (§5.6 parity) treated as a silent
/// skip — there is simply nothing to attribute to the idle agent.
const NO_CHANGES_MARK: &str = "No uncommitted changes found";

/// Diff output cap (64 KB): keep prompts sane when the worktree is very dirty.
const DIFF_CAP_BYTES: usize = 64 * 1024;
/// Repo-root `AGENTS.md` cap (8 KB): enough context without ballooning prompts.
const AGENTS_MD_CAP_BYTES: usize = 8 * 1024;
/// Recent commit subjects for style mimicry (~10 commits).
const RECENT_COMMITS_LIMIT: usize = 10;
/// Generation timeout (~30 s) — acceptable latency on idle before falling
/// back. Tests compress it via [`crate::Services::with_auto_commit_timeout_ms`].
///
/// This is auto-commit's OWN budget, passed as `agent.completeOnce`'s
/// `timeoutMs` (§5.32) — generation never runs through the interactive
/// prompt-enhancement RPC or its budget, and a timeout here degrades to the
/// deterministic [`Services::build_auto_commit_subject`] fallback rather than
/// failing the commit (monorepo#4032). Must stay within §5.32's 120 s
/// `timeoutMs` cap, which the op silently applies.
const GENERATION_TIMEOUT_MS: u64 = 30_000;

/// Cap on the raw LLM output logged (at debug level) when parsing fails.
const RAW_OUTPUT_LOG_CAP_CHARS: usize = 500;

/// Whether the `agent:idle` `finishReason` is a normal turn-end we should
/// auto-commit on. Anything outside this allowlist (or missing) is treated as
/// a non-normal terminal state and skipped (TS
/// `handleAgentIdleAutoCommit` finish-reason gate).
fn is_normal_finish_reason(reason: Option<&str>) -> bool {
    matches!(
        reason,
        Some("end_turn" | "max_tokens" | "max_turn_requests" | "stream_complete")
    )
}

/// Whether an agent's display name was set explicitly by an `agent.rename` /
/// explicit-name caller (i.e., isn't the autogenerated `Agent xxxxxx` form).
/// Mirrors the TS `meaningfulAgentName` guard the auto-commit subject-line
/// fallback uses.
fn is_meaningful_agent_name(session: &AgentSession) -> bool {
    session.name_explicitly_set && !session.name.trim().is_empty()
}

/// Collapse whitespace runs (including embedded newlines) into single spaces,
/// trim, and clamp to [`SUBJECT_MAX_CHARS`] characters. Mirrors the TS
/// `buildCommitMessage` subject hygiene so trailers can be appended cleanly.
fn normalize_subject(raw: &str) -> String {
    let collapsed: String = raw.split_whitespace().collect::<Vec<_>>().join(" ");
    collapsed.chars().take(SUBJECT_MAX_CHARS).collect()
}

/// Build a prompt context string for commit-message generation: uncommitted diff
/// (capped), recent commit subjects (style mimicry), repo-root `AGENTS.md` (if
/// present, capped), and task/agent hints.
fn build_message_prompt(
    diff_text: &str,
    recent_commits: &[String],
    agents_md: Option<&str>,
    task_title: Option<&str>,
    agent_name: &str,
) -> String {
    let mut parts = Vec::new();
    parts.push(format!("# Uncommitted Changes\n\n```\n{diff_text}\n```"));
    if !recent_commits.is_empty() {
        parts.push(format!(
            "\n# Recent Commit Messages (for style reference)\n\n{}",
            recent_commits
                .iter()
                .map(|s| format!("- {s}"))
                .collect::<Vec<_>>()
                .join("\n")
        ));
    }
    if let Some(md) = agents_md {
        parts.push(format!("\n# Repository Conventions (AGENTS.md)\n\n{md}"));
    }
    if let Some(title) = task_title {
        parts.push(format!(
            "\n# Task Context\n\nTask: {title}\nAgent: {agent_name}"
        ));
    } else {
        parts.push(format!("\n# Agent\n\nAgent: {agent_name}"));
    }
    parts.join("\n")
}

/// Deserialized shape of the model's JSON reply (the `commit-message.md`
/// output contract): a required subject plus an optional body.
#[derive(serde::Deserialize)]
struct CommitMessageReply {
    subject: String,
    body: Option<String>,
}

/// Parse the LLM output for the `{"subject", "body"?}` JSON object requested
/// by `commit-message.md`. Tolerates surrounding prose and code fences by
/// attempting a deserialize at each `{` until one parses with a non-empty
/// subject (trailing text after the object is ignored; a parseable candidate
/// with a blank subject is skipped like a malformed one). Returns the
/// composed message — `subject`, or `subject\n\nbody` when a non-empty body
/// is present — or `None` when no candidate yields a non-empty subject.
fn parse_commit_message_json(output: &str) -> Option<String> {
    for (idx, _) in output.match_indices('{') {
        let mut stream =
            serde_json::Deserializer::from_str(&output[idx..]).into_iter::<CommitMessageReply>();
        if let Some(Ok(reply)) = stream.next() {
            let subject = reply.subject.trim();
            if subject.is_empty() {
                continue;
            }
            let body = reply.body.as_deref().map_or("", str::trim);
            return Some(if body.is_empty() {
                subject.to_string()
            } else {
                format!("{subject}\n\n{body}")
            });
        }
    }
    None
}

impl Services {
    /// Spawn the LNI-1 auto-commit worker: subscribe to `agent:idle` across
    /// every workspace and, for each normally-finished task-linked agent,
    /// invoke [`crate::Services::git_agent_commit`] so the commit carries the
    /// `Agent-Id:` and `Linked-Note-Id:` trailers. No-op-safe when no event
    /// bus is wired. Returns the task handle so the composition root can hold
    /// it for the process lifetime.
    pub fn spawn_auto_commit_loop(&self) -> tokio::task::JoinHandle<()> {
        let Some(bus) = self.event_bus.clone() else {
            tracing::info!("auto-commit-on-idle loop disabled: no event bus");
            return tokio::spawn(async {});
        };
        let services = self.clone();
        tokio::spawn(async move {
            // Span every workspace (workspace_id = None) and deliver each
            // matched event immediately (batch_window = None) so auto-commit
            // races no other turn-end work.
            let filter = SubscriptionFilter {
                event_types: vec![AGENT_IDLE.to_string()],
                ..Default::default()
            };
            let mut sub = bus.subscribe(filter);
            while let Some(events) = sub.recv().await {
                for event in events {
                    services.handle_agent_idle_auto_commit(&event).await;
                }
            }
        })
    }

    /// One-shot handler for a single `agent:idle` event. Logs and swallows
    /// every error so a single malformed event never tears down the worker.
    pub(crate) async fn handle_agent_idle_auto_commit(&self, event: &Event) {
        if event.event_type != AGENT_IDLE {
            return;
        }
        let Some(agent_id_str) = event.data.get("agentId").and_then(|v| v.as_str()) else {
            tracing::debug!("agent:idle missing agentId; skipping auto-commit");
            return;
        };
        let agent_id = AgentId::from(agent_id_str);
        let finish_reason = event.data.get("finishReason").and_then(|v| v.as_str());
        if !is_normal_finish_reason(finish_reason) {
            tracing::debug!(
                agent = %agent_id.0,
                reason = ?finish_reason,
                "auto-commit skipped: non-normal finishReason"
            );
            return;
        }
        // Load the idle session. A best-effort lookup: a missing session (e.g.,
        // racing delete) is not an auto-commit error — just log and skip.
        let session = match self.store().get_agent_session(&agent_id).await {
            Ok(s) => s,
            Err(e) => {
                tracing::debug!(
                    agent = %agent_id.0,
                    error = %e,
                    "auto-commit skipped: session lookup failed"
                );
                return;
            }
        };
        if session.skip_auto_commit {
            tracing::debug!(
                agent = %agent_id.0,
                "auto-commit skipped: session opted out via skipAutoCommit"
            );
            return;
        }

        // Resolve the checkout path for generation + fallback. Direct
        // checkouts may persist only `repositoryPath` (monorepo#3778), and
        // `git_agent_commit` itself resolves via `git_ops::worktree_path`
        // (worktreePath → repositoryPath), so skipping here would be the
        // only thing blocking auto-commit for them.
        let worktree_path = match self.store().get_workspace(&session.workspace_id).await {
            Ok(ws) => {
                if let Some(p) = ws.effective_path().map(PathBuf::from) {
                    p
                } else {
                    tracing::debug!(
                        agent = %agent_id.0,
                        workspace = %session.workspace_id.0,
                        "auto-commit skipped: no on-disk checkout path"
                    );
                    return;
                }
            }
            Err(e) => {
                tracing::warn!(
                    agent = %agent_id.0,
                    workspace = %session.workspace_id.0,
                    error = %e,
                    "auto-commit failed: could not load workspace"
                );
                return;
            }
        };

        let linked_note_id = session.task_note_id.clone();
        // Attempt LLM generation; fall back to deterministic subject on any failure.
        let message = if let Some(msg) = self
            .generate_auto_commit_message(&worktree_path, &session, linked_note_id.as_ref())
            .await
        {
            msg
        } else {
            tracing::debug!(
                agent = %agent_id.0,
                workspace = %session.workspace_id.0,
                "auto-commit using fallback subject"
            );
            self.build_auto_commit_subject(&session, linked_note_id.as_ref())
                .await
        };

        match self
            .git_agent_commit(
                session.workspace_id.clone(),
                message,
                Some(agent_id.clone()),
                linked_note_id.clone(),
                None,
                false,
                None,
            )
            .await
        {
            Ok(outcome) => {
                tracing::debug!(
                    agent = %agent_id.0,
                    workspace = %session.workspace_id.0,
                    hash = %outcome.hash,
                    files = outcome.file_count,
                    "auto-commit on agent idle"
                );
            }
            Err(Error::Internal(msg))
                if msg.contains(AUTO_COMMIT_DISABLED_MARK)
                    || msg.contains(NO_CHANGES_MARK)
                    || msg.contains(CLEAN_TREE_ERROR)
                    || msg.contains(PARTIAL_MERGE_COMMIT_ERROR) =>
            {
                tracing::debug!(
                    agent = %agent_id.0,
                    workspace = %session.workspace_id.0,
                    "auto-commit skipped: {msg}"
                );
            }
            Err(e) => {
                tracing::warn!(
                    agent = %agent_id.0,
                    workspace = %session.workspace_id.0,
                    error = %e,
                    "auto-commit failed"
                );
            }
        }
    }

    /// Resolve the auto-commit fallback subject (taskTitle → meaningful agent
    /// name → `"Agent changes"`), normalized to one line of ≤ 72 chars.
    pub(crate) async fn build_auto_commit_subject(
        &self,
        session: &AgentSession,
        linked_note_id: Option<&NoteId>,
    ) -> String {
        if let Some(note_id) = linked_note_id {
            if let Ok(note) = self.store().get_note(&session.workspace_id, note_id).await {
                let title = note.title.trim();
                if !title.is_empty() {
                    return normalize_subject(title);
                }
            }
        }
        if is_meaningful_agent_name(session) {
            return normalize_subject(&session.name);
        }
        DEFAULT_SUBJECT.to_string()
    }

    /// Generate a commit message via LLM given the workspace worktree, session,
    /// and linked note. Returns `None` on any failure (missing auggie CLI,
    /// timeout, unparseable output, no uncommitted changes), logging the failure
    /// at debug/warn level. The caller should fall back to
    /// [`Self::build_auto_commit_subject`] when `None` is returned.
    async fn generate_auto_commit_message(
        &self,
        worktree_path: &std::path::Path,
        session: &AgentSession,
        linked_note_id: Option<&NoteId>,
    ) -> Option<String> {
        // Skip generation entirely when there are no uncommitted changes.
        // Use diff_index_to_workdir (includes untracked) since auto-commit
        // stages everything via git_agent_commit.
        let diff_files = match intent_git::diff::diff_index_to_workdir(worktree_path) {
            Ok(files) => files,
            Err(e) => {
                tracing::debug!(
                    workspace = %session.workspace_id.0,
                    error = %e,
                    "generate_auto_commit_message: diff failed"
                );
                return None;
            }
        };
        if diff_files.is_empty() {
            tracing::debug!(
                workspace = %session.workspace_id.0,
                "generate_auto_commit_message: no changes, skipping generation"
            );
            return None;
        }

        // Build diff text (capped at DIFF_CAP_BYTES).
        let mut diff_text = String::new();
        for fd in &diff_files {
            let line = format!("{} | +{} -{}\n", fd.path, fd.additions, fd.deletions);
            if diff_text.len() + line.len() > DIFF_CAP_BYTES {
                diff_text.push_str("... (diff truncated)\n");
                break;
            }
            diff_text.push_str(&line);
        }

        // Recent commit subjects for style mimicry — metadata only, no need
        // for the per-commit tree diffs (`include_files = false`).
        let recent_commits =
            intent_git::history::history_since(worktree_path, None, RECENT_COMMITS_LIMIT, false)
                .ok()
                .map(|commits| commits.into_iter().map(|c| c.message).collect::<Vec<_>>())
                .unwrap_or_default();

        // Repo-root AGENTS.md (if present, capped).
        let agents_md = worktree_path
            .join("AGENTS.md")
            .exists()
            .then(|| {
                std::fs::read_to_string(worktree_path.join("AGENTS.md"))
                    .ok()
                    .map(|content| {
                        if content.len() > AGENTS_MD_CAP_BYTES {
                            // UTF-8 safe truncation: find last char boundary within cap
                            let mut end = AGENTS_MD_CAP_BYTES.min(content.len());
                            while end > 0 && !content.is_char_boundary(end) {
                                end -= 1;
                            }
                            format!("{}... (truncated)", &content[..end])
                        } else {
                            content
                        }
                    })
            })
            .flatten();

        // Task title (if linked).
        let task_title = if let Some(note_id) = linked_note_id {
            self.store()
                .get_note(&session.workspace_id, note_id)
                .await
                .ok()
                .map(|n| n.title)
        } else {
            None
        };

        // Compose prompt.
        let prompt = build_message_prompt(
            &diff_text,
            &recent_commits,
            agents_md.as_deref(),
            task_title.as_deref(),
            &session.name,
        );
        // `commit-message` is a non-interactive background body with no
        // feature-gated sections, so default flags are always correct here.
        // Pinned to the session's stamped harness version (H2): the
        // background body tracks the doctrine the owning session runs on.
        let system_prompt = get_instruction_with_common_for(
            crate::harness::resolve_entry(&session.harness_version)
                .doctrine
                .instructions,
            "commit-message",
            &intent_core::settings_file::AgentFeaturesSettings::default(),
        );

        // Call agent_complete_once_op. With no explicit model, the `commit`
        // quick-action type lets the op apply the user's
        // `quickActions.typeOverrides["commit"]` (monorepo#1734).
        let result = self
            .agent_complete_once_op(
                prompt,
                Some(system_prompt),
                None,
                Some("commit".to_string()),
                Some(session.workspace_id.clone()),
                Some(self.auto_commit_timeout_ms.unwrap_or(GENERATION_TIMEOUT_MS)),
            )
            .await;

        match result {
            Ok(value) => {
                let text = value["text"].as_str().unwrap_or("");
                if let Some(msg) = parse_commit_message_json(text) {
                    tracing::debug!(
                        workspace = %session.workspace_id.0,
                        "generate_auto_commit_message: success"
                    );
                    Some(msg)
                } else {
                    tracing::warn!(
                        workspace = %session.workspace_id.0,
                        "generate_auto_commit_message: unparseable output (no JSON object with a non-empty subject)"
                    );
                    let raw: String = text.chars().take(RAW_OUTPUT_LOG_CAP_CHARS).collect();
                    tracing::debug!(
                        workspace = %session.workspace_id.0,
                        raw = %raw,
                        "generate_auto_commit_message: unparseable raw output (truncated)"
                    );
                    None
                }
            }
            Err(e) => {
                tracing::warn!(
                    workspace = %session.workspace_id.0,
                    error = %e,
                    "generate_auto_commit_message: generation failed"
                );
                None
            }
        }
    }
}

#[cfg(test)]
mod tests;
